#!/usr/bin/env python3
"""
chrome_forge.py

Lightweight Chrome extension generator prototype.

Run: `python3 chrome_forge.py` and follow the prompt.
The script will create/overwrite the `generated_extension/` folder.
"""
import os
import json
import re
import shutil
import sys
from pathlib import Path


def detect_features(prompt: str):
    p = prompt.lower()
    features = {
        "popup": False,
        "content_script": False,
        "background": False,
        "permissions": set(),
        "css": False,
        "notes": [],
    }

    # Popup detection
    if any(w in p for w in ["popup", "button", "menu", "show a popup", "open a popup", "click the button", "toolbar button"]):
        features["popup"] = True

    # Content script detection
    if any(w in p for w in ["highlight", "modify", "change", "replace", "dom", "page", "webpage", "on any website", "content script", "inject", "highlight all", "phone number", "phone numbers", "find", "extract"]):
        features["content_script"] = True

    # Background detection
    if any(w in p for w in ["background", "block", "blocking", "alarm", "timer", "on startup", "every time the browser opens", "automate", "scheduler", "cron", "webrequest"]):
        features["background"] = True

    # CSS/styling detection
    if any(w in p for w in ["css", "style", "theme", "color", "blue", "red", "dark mode", "styling"]):
        features["css"] = True

    # Permissions detection
    perm_map = {
        "tabs": ["tab", "tabs"],
        "storage": ["save", "storage", "localstorage", "local storage"],
        "scripting": ["inject script", "scripting", "execute script"],
        "webRequest": ["webrequest", "web request", "block", "blocking"],
        "activeTab": ["active tab", "activeTab"],
        "alarms": ["alarm", "alarms", "timer"],
    }
    for perm, kws in perm_map.items():
        if any(k in p for k in kws):
            features["permissions"].add(perm)

    # Host permissions detection (simple domain extraction)
    hosts = set()
    for dom in re.findall(r"(?:https?://)?(?:www\.)?([a-z0-9\-]+\.(?:com|org|net|io|edu))", p):
        hosts.add(f"*://{dom}/*")
    if hosts:
        features["permissions"].add("host_permissions")
        features["hosts"] = list(hosts)

    # Specific behaviors / hints
    if "phone" in p and "highlight" in p:
        features["notes"].append("Will highlight phone numbers using a regex in content script.")

    if "today" in p or "date" in p or "current date" in p:
        features["notes"].append("Popup will show today's date.")

    if "change all webpage text to blue" in p or "text to blue" in p:
        features["notes"].append("Content script will set body color to blue.")

    if "block facebook" in p or "block tiktok" in p or "block instagram" in p:
        features["notes"].append("Background will include placeholder blocking rules and host permissions.")
        # add declarativeNetRequest permission for blocking hints
        features["permissions"].add("declarativeNetRequest")

    return features


def build_manifest(name: str, features: dict):
    manifest = {
        "manifest_version": 3,
        "name": name,
        "version": "1.0",
        "description": "Generated by ChromeForge prototype.",
        "action": {},
    }

    if features.get("popup"):
        manifest["action"]["default_popup"] = "popup.html"

    # Permissions
    perms = [p for p in features.get("permissions", set()) if p != "host_permissions"]
    if perms:
        manifest["permissions"] = sorted(perms)

    # Background service worker
    if features.get("background"):
        manifest["background"] = {"service_worker": "background.js"}

    # Content scripts
    if features.get("content_script"):
        manifest["content_scripts"] = [{
            "matches": ["<all_urls>"],
            "js": ["content.js"],
            "run_at": "document_idle"
        }]

    # Host permissions
    if "hosts" in features and features.get("hosts"):
        manifest["host_permissions"] = features.get("hosts")

    return manifest


def write_files(outdir: Path, features: dict, prompt: str):
    outdir.mkdir(parents=True, exist_ok=True)

    # manifest
    name = (prompt.strip()[:50] or "ChromeForge Extension").strip()
    manifest = build_manifest(name, features)
    (outdir / "manifest.json").write_text(json.dumps(manifest, indent=2))

    # styles.css
    if features.get("css") or features.get("popup"):
        css = "body{font-family:Arial,Helvetica,sans-serif;margin:12px;color:#111;}\n.button{padding:8px 12px;border-radius:4px;background:#007bff;color:#fff;border:none;cursor:pointer;}\n.highlighted{background:yellow;padding:0 2px;border-radius:2px;}\n"
        (outdir / "styles.css").write_text(css)

    # popup
    if features.get("popup"):
        popup_html = (
            "<!doctype html>\n<html>\n<head>\n<meta charset=\"utf-8\">\n<title>Popup</title>\n<link rel=\"stylesheet\" href=\"styles.css\">\n</head>\n<body>\n<div id=\"app\">\n  <h3>ChromeForge Popup</h3>\n  <div id=\"output\"></div>\n  <button id=\"act\" class=\"button\">Run</button>\n</div>\n<script src=\"popup.js\"></script>\n</body>\n</html>"
        )
        (outdir / "popup.html").write_text(popup_html)

        popup_js_lines = [
            "document.getElementById('act').addEventListener('click', async () => {",
            "  const out = document.getElementById('output');",
        ]
        if any('date' in n.lower() or 'today' in n.lower() for n in features.get('notes', [])) or 'date' in prompt.lower() or 'today' in prompt.lower():
            popup_js_lines.append("  out.textContent = 'Today: ' + new Date().toLocaleString();")
        elif features.get('content_script') and 'change all webpage text to blue' in prompt.lower():
            popup_js_lines.append("  // send message to content script to turn text blue")
            popup_js_lines.append("  chrome.tabs.query({active:true,currentWindow:true}, tabs => { chrome.tabs.sendMessage(tabs[0].id, {action:'turn-blue'}); });")
        else:
            popup_js_lines.append("  out.textContent = 'Action executed.';")
        popup_js_lines.append("});")
        (outdir / "popup.js").write_text('\n'.join(popup_js_lines))

    # content script
    if features.get("content_script"):
        p = prompt.lower()
        content_lines = []
        if "phone" in p and "highlight" in p:
            content_lines = [
                "// Highlights phone numbers on the page",
                "(function(){",
                "  const PHONE_RE = /\\b(\\+?\\d[\\d\-() ]{6,}\\d)\\b/g;",
                "  function walk(node){",
                "    if(node.nodeType === 3){ // text",
                "      const parent = node.parentNode;",
                "      if(!parent) return;",
                "      const s = node.nodeValue;",
                "      if(PHONE_RE.test(s)){",
                "        const span = document.createElement('span');",
                "        span.innerHTML = s.replace(PHONE_RE, '<span class=\\'highlighted\\'>$1</span>');",
                "        parent.replaceChild(span, node);",
                "      }",
                "    } else {",
                "      for(let i=0;i<node.childNodes.length;i++) walk(node.childNodes[i]);",
                "    }",
                "  }",
                "  walk(document.body);",
                "})();",
            ]
        elif 'change all webpage text to blue' in p or 'text to blue' in p:
            content_lines = [
                "// Changes all page text color to blue",
                "document.documentElement.style.color = 'blue';",
            ]
        else:
            content_lines = [
                "// Generic content script placeholder",
                "console.log('Content script injected');",
            ]

        # message listener for popup-triggered actions
        content_lines.append("
chrome.runtime.onMessage.addListener((msg, sender, sendResp) => {")
        content_lines.append("  if(msg && msg.action === 'turn-blue'){ document.documentElement.style.color = 'blue'; }")
        content_lines.append("});")

        (outdir / "content.js").write_text('\n'.join(content_lines))

    # background script
    if features.get("background"):
        bg_lines = [
            "// Background service worker (placeholder)",
            "self.addEventListener('install', () => { console.log('Service worker installed'); });",
            "self.addEventListener('activate', () => { console.log('Service worker activated'); });",
        ]
        p = prompt.lower()
        # if blocking hint found, add sample dynamic rule (declarativeNetRequest)
        if any(x in p for x in ['block facebook', 'block tiktok', 'block instagram', 'block ']):
            bg_lines += [
                "// Example: install a declarativeNetRequest rule to block hosts (Chrome may require user consent)",
                "const RULE_ID = 1;",
                "chrome.declarativeNetRequest.updateDynamicRules({addRules:[{id:RULE_ID,priority:1,action:{type:'block'},condition:{urlFilter:'||facebook.com',resourceTypes:['main_frame']}}],removeRuleIds:[]}, () => { console.log('Attempted to add blocking rule'); });",
            ]

        (outdir / "background.js").write_text('\n'.join(bg_lines))

    print(f"Wrote files to {outdir}")


def main():
    # Accept a prompt via CLI arg for automation; otherwise interactive
    if len(sys.argv) > 1:
        prompt = ' '.join(sys.argv[1:])
        print(f"Using prompt from args: {prompt}")
    else:
        print('Describe the Chrome Extension you want to generate:')
        prompt = input('> ').strip()

    if not prompt:
        print('No prompt provided; using sample: "Popup showing today\'s date"')
        prompt = "Show a popup with today's date"

    features = detect_features(prompt)
    print('\nDetected features:')
    for k, v in features.items():
        if k == 'permissions':
            print(f"- permissions: {sorted(list(v))}")
        else:
            print(f"- {k}: {v}")

    outdir = Path.cwd() / 'generated_extension'
    # backup existing folder
    if outdir.exists():
        backup = Path.cwd() / 'generated_extension_backup'
        if backup.exists():
            shutil.rmtree(backup)
        shutil.move(str(outdir), str(backup))
        print(f"Existing 'generated_extension' moved to 'generated_extension_backup'")

    write_files(outdir, features, prompt)


if __name__ == '__main__':
    main()
